--- #YAML:1.0
name:                Authen-Tcpdmatch
version:             0.07
abstract:            Perl extension for parsing  hosts.allow  and  hosts.deny
license:             gpl
author:              
    - Ioannis Tambouras <ioannis@earthlink.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Attribute::Handlers:           0
    NetAddr::IP:                   3.14
    Parse::RecDescent:             0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
