--- #YAML:1.0
name: Authen-Tcpdmatch
version: 0.08
author:
  - Ioannis Tambouras <ioannis@cpan.org>
abstract: ~
license: gpl
requires:
  Attribute::Handlers: 0
  NetAddr::IP: 3.14
  Parse::RecDescent: 0
  perl: 5.6
recommends:
  Test::More: 0
  Test::Pod::Coverage: 1.06
provides:
  Authen::Tcpdmatch::Grammar:
    file: lib/Authen/Tcpdmatch/Grammar.pm
  Authen::Tcpdmatch::Tcpdmatch:
    file: lib/Authen/Tcpdmatch/Tcpdmatch.pm
    version: 0.04
  Authen::Tcpdmatch::TcpdmatchRD:
    file: lib/Authen/Tcpdmatch/TcpdmatchRD.pm
    version: 0.03
generated_by: Module::Build version 0.2611
